### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by BenHerbst** [yellowsink/WacomAreaX11#1]
I searched for a wacom gui configuration application for my herbstluftwm.
When I tried to install via pamac I get: httpfs2: HEAD: exchange: server error
HTTP/1.1 301 Moved Permanently

**Comment by yellowsink** [comment]
That's odd, and does belong on the AUR comments not here, but either way, can you send a full log / screenshot of an attempt to install the package?

**Comment by BenHerbst** [comment]
I can't post on Github as it is too long ( Maximum is 65536 characters ) And it is a big log with maybe 1000 lines? And I also don't know how to view it in english as it is german, and I am new to Manjaro.

**Comment by BenHerbst** [comment]
I can actually send it as a text file:
[log.txt](https://github.com/yellowsink/WacomAreaX11/files/8457417/log.txt)

**Comment by yellowsink** [comment]
I suggest you try the yay AUR helper instead?

**Comment by BenHerbst** [comment]
I don't really need this anymore as there is https://github.com/whjochim/xwacomcalibrate which is a very simple script that gives my wacom the current window as size. But thank you for your help.

**Comment by yellowsink** [comment]
:+1:

**Comment by BenHerbst** [comment]
There is no Xwacomcalibrate anymore, and I now use Pop!_OS with Gnome desktop, and there is only the option to set the Area to a screen not a single area / window, so this Application would be a nice solution to set it to an area via gui. Maybe package it as AppImage?

**Comment by yellowsink** [comment]
~~Once again, please try yay instead of pamac.~~

~~I do not trust pamac to work correctly, whereas I know that yay and paru both do.~~

OH MY GOD i am stupid lmao, sorry about that, I will look into popos compatible packaging :)
